fixups airconnect_installer

diff --git a/airconnect/airconnect_installer b/airconnect/airconnect_installer
--- a/airconnect/airconnect_installer
+++ b/airconnect/airconnect_installer
@@ -37,7 +37,7 @@ else
   USE_OUTPUT_DIR=false
 fi
 
-# Start installation or update process
+# Check if AirConnect is already installed
 if [ -d "${bindir}" ]; then
   printf "${GREEN}Updating AirConnect...${NC}\n"
 
@@ -94,13 +94,17 @@ if [ -d "${bindir}" ]; then
 else
   printf "${GREEN}Installing AirConnect...${NC}\n"
 
-  # Install necessary dependencies
-  if dpkg-query -W -f='${Status}' libssl1.1 2>/dev/null | grep -q "unknown ok not-installed"; then
-    printf "${YELLOW}Installing libssl1.1 dependency...${NC}\n"
-    if ! apt-get install -y libssl1.1; then
-      printf "${RED}ERROR: ${NC}Failed to install libssl1.1. Exiting.\n"
-      exit 1
+  # For Ubuntu 24.04+, skip libssl1.1 as it's not required
+  if ! grep -q "24.04" /etc/os-release; then
+    if dpkg-query -W -f='${Status}' libssl1.1 2>/dev/null | grep -q "unknown ok not-installed"; then
+      printf "${YELLOW}Installing libssl1.1 dependency...${NC}\n"
+      if ! apt-get install -y libssl1.1; then
+        printf "${RED}ERROR: ${NC}Failed to install libssl1.1. Exiting.\n"
+        exit 1
+      fi
     fi
+  else
+    printf "${YELLOW}Skipping libssl1.1 installation for Ubuntu 24.04+...${NC}\n"
   fi
 
   # Create necessary directories and download binaries
@@ -133,39 +137,4 @@ else
     }
 
     popd || {
-      printf "${RED}ERROR: ${NC}Failed to return to the previous directory. Exiting.\n"
-      exit 1
-    }
-  fi
-
-  # Download the systemd service file and set it up
-  pushd "${sysdir}" || {
-    printf "${RED}ERROR: ${NC}Failed to change directory to ${sysdir}. Exiting.\n"
-    exit 1
-  }
-
-  printf "${YELLOW}Downloading AirConnect systemd service file...${NC}\n"
-  curl ${CURL_FLAGS} --compressed -LO https://raw.githubusercontent.com/pheiduck/rpi_configs/main/airconnect/airupnp.service || {
-    printf "${RED}ERROR: ${NC}Failed to download systemd service file. Exiting.\n"
-    exit 1
-  }
-
-  popd || {
-    printf "${RED}ERROR: ${NC}Failed to return to the previous directory. Exiting.\n"
-    exit 1
-  }
-
-  # Reload systemd and enable the service
-  printf "${YELLOW}Enabling and starting AirConnect service...${NC}\n"
-  systemctl daemon-reload || {
-    printf "${RED}ERROR: ${NC}Failed to reload systemd daemon. Exiting.\n"
-    exit 1
-  }
-
-  systemctl enable --now airupnp || {
-    printf "${RED}ERROR: ${NC}Failed to enable and start AirConnect service. Exiting.\n"
-    exit 1
-  }
-
-  printf "${GREEN}AirConnect has been successfully installed.${NC}\n"
-fi
+      printf "${RED}ERROR: ${NC}Failed to return to the previous directory. Ex
